### PR TITLE
macros: fix references to `Error` in docstrings

### PR DESCRIPTION
**Pull request by birkenfeld**

### CODE REVIEW

**Comment by birkenfeld** [comment]
Fixes #53

**Review by thenorili — APPROVED** [review]
This looks good to me, thanks for correcting the mistaken documentation :)

**Review by thenorili — CHANGES_REQUESTED** [review]
I'd prefer if these two changes were squashed seeing as half of the first commit is overwritten by the second.

**Review by thenorili — APPROVED** [review]

**Comment by thenorili** [comment]
It says macros.rs has merge conflicts. I pulled it locally and don't see any, but there's nothing I can do from here. @birkenfeld will have to squash and rebase on their end. Sorry if you got spammed with my auto-merge stuff while I was trying to figure things out. This is ready to go when the conflicts are resolved.

**Pull request merged**
