### PR TITLE
fix(docs): enclose inline code in backticks

### LINKED ISSUE #169: docs: enclosing in backticks
Reading https://docs.rs/eyre/latest/eyre/struct.Report.html#display-representations I found that some items should better be enclosed in backticks.

image

I'll happily fix that, I merely want to ask in advance:

When enclosing parts of strings in backticks, do you then prefer **backticks + quotes**, or **only backticks**?

I personally prefer backticks + quotes, to signify _"this is code, but it's a string literal"_.

**Here an example (look out for the curly braces):**

1. **backticks + quotes**: When you print an error object using `"{}"` or `to_string()`, only the outermost underlying error is printed, not any of the lower level causes. This is exactly as if you had called the `Display` `impl` of the error from which you constructed your `eyre::Report`. [...] To print causes as well using eyre’s default formatting of causes, use the alternate selector `"{:#}"`.
2. **only backticks**: When you print an error object using `{}` or `to_string()`, only the outermost underlying error is printed, not any of the lower level causes. This is exactly as if you had called the `Display` `impl` of the error from which you constructed your `eyre::Report`. [...] To print causes as well using eyre’s default formatting of causes, use the alternate selector `{:#}`.

### PR DESCRIPTION
**Pull request by LeoniePhiline**
Fixes #169

Besides enclosing inline code in backticks, I also made two tiny documentation improvements - please let me know if you want them undone:

- In the `Report::msg` docs, the user is referred to `Report::new`. I changed this from plain inline code into a link.
- I expanded _"`Display` impl"_ to _"`Display` implementation"_, since `impl` is a Rust token, but 
  - _"`Display` `impl`"_ looked silly, and 
  - _"`impl Display`"_ disturbed the flow of reading.

### CODE REVIEW

**Comment by LeoniePhiline** [comment]
The CI failures confuse me. They seem unrelated?

**Review by pksunkara — APPROVED** [review]

**Comment by yaahc** [comment]
@LeoniePhiline I think we'll land 163 then you can go ahead and rebase on master

**Comment by yaahc** [comment]
turns out I was able to do the rebase myself easily ^_^

**Comment by LeoniePhiline** [comment]
Thank you! ☺️

**Pull request merged**
