### PR TITLE
Add 1-argument `ensure!($expr)`

### PR DESCRIPTION
**Pull request by sharnoff**
Amends a subltle difference from `anyhow`. This PR is basically duplicated from https://github.com/dtolnay/anyhow/pull/129.

### CODE REVIEW

**Comment by thenorili** [comment]
Hi! This seems like a small and useful change, maintaining that compatibility with anyhow's `ensure!`.

It looks like this failed CI due to some problems that weren't really your fault and now it's gone stale. Would you consider rebasing and updating the review now that tests are more stable and there are more folks around to handle contributions?

**Comment by sharnoff** [comment]
No worries :)

Rebased - no conflicts, didn't check if the changes are still valid

**Review by thenorili — APPROVED** [review]
This looks good to me! I've checked it against the upstream version and 'ensure'd it looks okay =] I did not have formal review powers before but now I do, so here goes nothing: ✅

**Comment by thenorili** [comment]
Thanks so much for the contribution! :D

**Pull request merged**
